pipeline {
    agent any

    


     environment {
       
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }


    stages {
        stage('checkout') {
            steps {
                 
                            git  'https://github.com/tisha938/jenkin.git'
                        }
                    
                }
            

        stage('Init') {
            steps{
                sh 'terraform init'
            }
            }
            
           
        
        stage('Plan') {
          steps{
                sh 'terraform plan -out=tfplan'
            }
           }
           

        stage('Apply') {
          
            
            steps {
                sh "terraform apply -auto-approve"
            }
        }
    }
        
        }
    

  
